### ISSUE TITLE
I think if you copy paste welcome message it triggers the function

### ISSUE THREAD

**Issue by m-althaf** [remixbruh/daddy-discord#1]
trigger the message when you encounter class="embedWrapper-lXpS3L embedFull-2tM8-- embed-IeVjo6 markup-2BOw-j" or css div name bcz otherwise if  someone copy paste the message it will be trigger.

**Comment by remix420** [comment]
> trigger the message when you encounter class="embedWrapper-lXpS3L embedFull-2tM8-- embed-IeVjo6 markup-2BOw-j" or css div name bcz otherwise if someone copy paste the message it will be trigger.

I dont think anyone would copy and paste the welcome message, but I just used the trigger words "and follow the" since it is kind of unique and simple, but I have thought about using another method/words to trigger the welcome message.
